"""
Recipes
Library with recipes
"""
##--Korean steamed eggs--#
#req: eggs
def steamed_eggs():
    print()
    print("INGREDIENTS:")
    print()
    print("2 Eggs")
    print("1/2 cup water")
    print("A pinch of salt")
    print("OPTIONAL: Black pepper")
    print("OPTIONAL: Chopped green onion")
    print()
    print("RECIPE FOR KOREAN STEAMED EGGS:")
    print()
    print("1. Crack two eggs in a small or medium microwave safe bowl. Whisk.")
    print("2. Add water, salt, and pepper. If you are adding green onions, now is the time to put them in.")
    print("3. Whisk.")
    print("4. Cover the bowl with another bowl. This is not required, but is reccomended for a better end product.")
    print("5. Pop it in the microwave.")
    print("6. Using a cloth or oven mitts, take the hot bowl out of the microwave.")
    print("7. Enjoy with rice or on its own.")
    print()
    print("Serves 1 person")

##--korean green onion or chive pancakes--#
#req: flour and green
def korean_pancakes():
    print()
    print("INGREDIENTS:")
    print()
    print("1/2 cup flour")
    print("1/2 cup water")
    print("7 green onions or 1 bunch of chi`ves")
    print("3 tbsp oil")
    print("A pinch of salt")
    print("OPTIONAL: Soy sauce")
    print("OPTIONAL: Vinegar")
    print()
    print("RECIPE FOR KOREAN GREEN ONION or CHIVE PANCAKES:")
    print()
    print("1. Chop green onion or chives into 3 inch pieces.")
    print("2. In a large bowl, mix water, flour and salt until there are no lumps")
    print("3. Add green onions or chives to the large bowl and gently coat the greens in the batter.")
    print("4. Heat a pan to medium heat and add the oil in.")
    print("5. Add around 1/2 cup of the batter to the pan. Flip when the bottom is golden.")
    print("6. Take the pancake off the pan and onto a plate. Cut it pizza slice style.")
    print("7. Enjoy!")
    print()
    print("OPTIONAL: Mix a tablespoon soy sauce with a splash of vinegar and use as a dipping sauce for a refreshing element.")
    print("Serves 2 people")

##--Sujebi--#
#req: flour and broth
def sujebi():
    print()
    print("INGREDIENTS:")
    print()
    print("FOR THE DOUGH:")
    print("1 cup flour")
    print("1/2 cup water")
    print("1 teaspoon salt")
    print()
    print("FOR THE BROTH:")
    print("4 cups of broth")
    print("Salt to taste")
    print("OPTIONAL: 2 green onions or 1/2 bunch chives")
    print("OPTIONAL: 1 onion")
    print("OPTIONAL: Anchovies")
    print("OPTIONAL: 1 piece dried kelp")
    print()
    print("RECIPE FOR SUJEBI(KOREAN HAND-TORN NOODLE SOUP):")
    print()
    print("1. In a medium pot, add the broth and set heat to medium low.")
    print("2. Chop green onions into 3 inch pieces.")
    print("3. Chop onion into 1/2 inch slices.")
    print("4. Add green onion/chives, onion, anchovies, and dried kelp into the broth and simmer for at least 10 minutes.")
    print("5. In a large bowl, mix flour, water and salt until it is well combined.")
    print("6. Bring the broth to a boil.")
    print("7. Using hands, break the dough into pieces 1/2 inch thick, depending on preference.")
    print("8. Cook noodles until fully cooked and serve.")
    print()
    print("Serves 4 people")

##--egg soup--#
#req: broth and eggs
def egg_soup():
    print()
    print("INGREDIENTS:")
    print()
    print("2 eggs")
    print("2 cups broth")
    print("Salt to taste")
    print("OPTIONAL: 1 green onion")
    print()
    print("RECIPE FOR SIMPLE EGG SOUP:")
    print()
    print("1. Chop green onions into 3 inch pieces.")
    print("2. Add broth and green onions to a saucepan and bring to a boil.")
    print("3. While waiting for the broth to boil, crack and whisk eggs in a bowl.")
    print("4. When the broth boils, pour the egg in.")
    print("5. Serve and enjoy!.")
    print()
    print("Serves 2 people")
